[project]
name = "rp-to-strong-rp-api-service"
version = "0.1.0"
description = "API consumer for training.rpstrength.com"
requires-python = ">=3.12"
dependencies = ["aiofiles>=25.1.0", "aiohttp>=3.13.3", "pydantic>=2.12.5"]
