[project]
name = "embeddings"
version = "0.1.0"
description = "Embedding library for hevy and rp"
requires-python = ">=3.12"
dependencies = [
  "pydantic~=2.12",
  "aiofiles>=25.1.0",
  "aiohttp>=3.13.3",
  "aiohttp-retry>=2.9.1",
  "pydantic>=2.12.5",
  "transformers>=5.2.0",
  "polars>=1.38.1",
  "sentence-transformers>=5.2.3",
]

[project.optional-dependencies]
cpu = ["torch>=2.10.0"]
cu130 = ["torch>=2.10.0"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cu130" }]]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu130", extra = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
